// Licensed Materials - Property of IBM
//
// (C) Copyright IBM Corp. 2005, 2011 All Rights Reserved
//
// US Government Users Restricted Rights - Use, duplicate or
// disclosure restricted by GSA ADP Schedule Contract with
// IBM Corp.
// IBM_COPYRIGHT_END

#pragma namespace ("root/tivoli/cit/sw")

class InstalledSoftware as $InstalledSoftware {
	[key]
	string Code;
	string Name;
	string Vendor;
	string Version;
	string InstallLocation;
	string InstallDate;
	string Description;
};

instance of Tivoli_ObjectProvider as $CIT_Provider
{
	Name = "CIT_Provider";
	Version = "1.0.0";
	ClassName = "com.ibm.sysmgmt.uim.provider.cit.sw.SWProvider";
};

instance of Tivoli_ClassProvider 
{
	Class = $InstalledSoftware;
	Provider = $CIT_Provider;
};