#!/bin/sh

CMD=$1
DIR=`dirname $CMD`

cd $DIR
. ./setupCmdLine

touch -C 1252 @output.file@

echo "WAS_HOME=$WAS_HOME\n" >>  @output.file@
echo "USER_INSTALL_ROOT=$USER_INSTALL_ROOT\n" >>  @output.file@
echo "WAS_CELL=$WAS_CELL\n" >>  @output.file@
echo "WAS_NODE=$WAS_NODE\n" >>  @output.file@

