--------------- Begin Copyright - Do not add comments here --------------
--
-- Licensed Materials - Property of IBM
--
-- Restricted Materials of IBM
--
-- Virtual Member Manager
--
-- (C) Copyright IBM Corp. 2005, 2010
--
-- US Government Users Restricted Rights - Use, duplication or
-- disclosure restricted by GSA ADP Schedule Contract with
-- IBM Corp.
--
----------------------------- End Copyright -----------------------------
ALTER TABLE @dbschema.@LAPROP
	ADD (CONSTRAINT WIMF_52
		FOREIGN KEY(TYPE_ID)
			REFERENCES @dbschema.@LAPROPTYPE);


ALTER TABLE @dbschema.@LAPROPENT
	ADD (CONSTRAINT WIMF_53
		FOREIGN KEY(PROP_ID)
			REFERENCES @dbschema.@LAPROP
			ON DELETE CASCADE);


ALTER TABLE @dbschema.@LALONGPROP
	ADD (CONSTRAINT WIMF_54
		FOREIGN KEY(PROP_ID)
			REFERENCES @dbschema.@LAPROP
			ON DELETE CASCADE);
			
			
ALTER TABLE @dbschema.@LALONGPROP
	ADD (CONSTRAINT WIMF_55
		FOREIGN KEY(TYPE_ID)
			REFERENCES @dbschema.@LAPROPTYPE);


ALTER TABLE @dbschema.@LALONGPROP
	ADD (CONSTRAINT WIMF_56
		FOREIGN KEY(ENTITY_ID)
			REFERENCES @dbschema.@LAENTITY
			ON DELETE CASCADE);
			
			
ALTER TABLE @dbschema.@LALONGPROP
	ADD (CONSTRAINT WIMF_57
		FOREIGN KEY(COMPOSITE)
			REFERENCES @dbschema.@LACOMPPROP
			ON DELETE CASCADE);
			
			
ALTER TABLE @dbschema.@LABLOBPROP
	ADD (CONSTRAINT WIMF_58
		FOREIGN KEY(PROP_ID)
			REFERENCES @dbschema.@LAPROP
			ON DELETE CASCADE);
			
			
ALTER TABLE @dbschema.@LABLOBPROP
	ADD (CONSTRAINT WIMF_59
		FOREIGN KEY(TYPE_ID)
			REFERENCES @dbschema.@LAPROPTYPE);


ALTER TABLE @dbschema.@LABLOBPROP
	ADD (CONSTRAINT WIMF_60
		FOREIGN KEY(ENTITY_ID)
			REFERENCES @dbschema.@LAENTITY
			ON DELETE CASCADE);
			
			
ALTER TABLE @dbschema.@LABLOBPROP
	ADD (CONSTRAINT WIMF_61
		FOREIGN KEY(COMPOSITE)
			REFERENCES @dbschema.@LACOMPPROP
			ON DELETE CASCADE);


ALTER TABLE @dbschema.@LADBLPROP
	ADD (CONSTRAINT WIMF_62
		FOREIGN KEY(PROP_ID)
			REFERENCES @dbschema.@LAPROP
			ON DELETE CASCADE);
			
			
ALTER TABLE @dbschema.@LADBLPROP
	ADD (CONSTRAINT WIMF_63
		FOREIGN KEY(TYPE_ID)
			REFERENCES @dbschema.@LAPROPTYPE);


ALTER TABLE @dbschema.@LADBLPROP
	ADD (CONSTRAINT WIMF_64
		FOREIGN KEY(ENTITY_ID)
			REFERENCES @dbschema.@LAENTITY
			ON DELETE CASCADE);
			
			
ALTER TABLE @dbschema.@LADBLPROP
	ADD (CONSTRAINT WIMF_65
		FOREIGN KEY(COMPOSITE)
			REFERENCES @dbschema.@LACOMPPROP
			ON DELETE CASCADE);


ALTER TABLE @dbschema.@LATSPROP
	ADD (CONSTRAINT WIMF_66
		FOREIGN KEY(PROP_ID)
			REFERENCES @dbschema.@LAPROP
			ON DELETE CASCADE);
			
			
ALTER TABLE @dbschema.@LATSPROP
	ADD (CONSTRAINT WIMF_67
		FOREIGN KEY(TYPE_ID)
			REFERENCES @dbschema.@LAPROPTYPE);


ALTER TABLE @dbschema.@LATSPROP
	ADD (CONSTRAINT WIMF_68
		FOREIGN KEY(ENTITY_ID)
			REFERENCES @dbschema.@LAENTITY
			ON DELETE CASCADE);
			
			
ALTER TABLE @dbschema.@LATSPROP
	ADD (CONSTRAINT WIMF_69
		FOREIGN KEY(COMPOSITE)
			REFERENCES @dbschema.@LACOMPPROP
			ON DELETE CASCADE);


ALTER TABLE @dbschema.@LAINTPROP
	ADD (CONSTRAINT WIMF_70
		FOREIGN KEY(PROP_ID)
			REFERENCES @dbschema.@LAPROP
			ON DELETE CASCADE);
			
			
ALTER TABLE @dbschema.@LAINTPROP
	ADD (CONSTRAINT WIMF_71
		FOREIGN KEY(TYPE_ID)
			REFERENCES @dbschema.@LAPROPTYPE);


ALTER TABLE @dbschema.@LAINTPROP
	ADD (CONSTRAINT WIMF_72
		FOREIGN KEY(ENTITY_ID)
			REFERENCES @dbschema.@LAENTITY
			ON DELETE CASCADE);
			
			
ALTER TABLE @dbschema.@LAINTPROP
	ADD (CONSTRAINT WIMF_73
		FOREIGN KEY(COMPOSITE)
			REFERENCES @dbschema.@LACOMPPROP
			ON DELETE CASCADE);


ALTER TABLE @dbschema.@LAREFPROP
	ADD (CONSTRAINT WIMF_74
		FOREIGN KEY(PROP_ID)
			REFERENCES @dbschema.@LAPROP
			ON DELETE CASCADE);
			
			
ALTER TABLE @dbschema.@LAREFPROP
	ADD (CONSTRAINT WIMF_75
		FOREIGN KEY(TYPE_ID)
			REFERENCES @dbschema.@LAPROPTYPE);


ALTER TABLE @dbschema.@LAREFPROP
	ADD (CONSTRAINT WIMF_76
		FOREIGN KEY(ENTITY_ID)
			REFERENCES @dbschema.@LAENTITY
			ON DELETE CASCADE);
			
			
ALTER TABLE @dbschema.@LAREFPROP
	ADD (CONSTRAINT WIMF_77
		FOREIGN KEY(COMPOSITE)
			REFERENCES @dbschema.@LACOMPPROP
			ON DELETE CASCADE);


ALTER TABLE @dbschema.@LASTRPROP
	ADD (CONSTRAINT WIMF_78
		FOREIGN KEY(PROP_ID)
			REFERENCES @dbschema.@LAPROP
			ON DELETE CASCADE);
			
			
ALTER TABLE @dbschema.@LASTRPROP
	ADD (CONSTRAINT WIMF_79
		FOREIGN KEY(TYPE_ID)
			REFERENCES @dbschema.@LAPROPTYPE);


ALTER TABLE @dbschema.@LASTRPROP
	ADD (CONSTRAINT WIMF_80
		FOREIGN KEY(ENTITY_ID)
			REFERENCES @dbschema.@LAENTITY
			ON DELETE CASCADE);
			
			
ALTER TABLE @dbschema.@LASTRPROP
	ADD (CONSTRAINT WIMF_81
		FOREIGN KEY(COMPOSITE)
			REFERENCES @dbschema.@LACOMPPROP
			ON DELETE CASCADE);


ALTER TABLE @dbschema.@LACOMPREL
	ADD (CONSTRAINT WIMF_82
		FOREIGN KEY(COMPOSITE_ID)
			REFERENCES @dbschema.@LAPROP
			ON DELETE CASCADE);


ALTER TABLE @dbschema.@LACOMPREL
	ADD (CONSTRAINT WIMF_83
		FOREIGN KEY(COMPONENT_ID)
			REFERENCES @dbschema.@LAPROP
			ON DELETE CASCADE);
			
			
ALTER TABLE @dbschema.@LACOMPPROP
	ADD (CONSTRAINT WIMF_84
		FOREIGN KEY(PROP_ID)
			REFERENCES @dbschema.@LAPROP
			ON DELETE CASCADE);
			
ALTER TABLE @dbschema.@LACOMPPROP
	ADD (CONSTRAINT WIMF_85
		FOREIGN KEY(ENTITY_ID)
			REFERENCES @dbschema.@LAENTITY
			ON DELETE CASCADE);
			
ALTER TABLE @dbschema.@LACOMPPROP
	ADD (CONSTRAINT WIMF_86
		FOREIGN KEY(COMPOSITE_ID)
			REFERENCES @dbschema.@LACOMPPROP
			ON DELETE CASCADE);
