CREATE DATABASE SDOREP WITH LOG;

CREATE SCHEMA AUTHORIZATION SDOREP;

CREATE TABLE SDOREP.bytestore
  (NAME CHARACTER VARYING(250) NOT NULL,
   BYTES BLOB,
   TIMESTAMP1 INT8 NOT NULL);

ALTER TABLE SDOREP.bytestore ADD CONSTRAINT
  (PRIMARY KEY (NAME) CONSTRAINT PK_BYTESTORE);
