--------------- Begin Copyright - Do not add comments here --------------
--
-- Licensed Materials - Property of IBM
--
-- Restricted Materials of IBM
--
-- Virtual Member Manager
--
-- (C) Copyright IBM Corp. 2005, 2010
--
-- US Government Users Restricted Rights - Use, duplication or
-- disclosure restricted by GSA ADP Schedule Contract with
-- IBM Corp.
--
----------------------------- End Copyright -----------------------------
ALTER TABLE @dbschema.@DBPROP ADD CONSTRAINT 
	(FOREIGN KEY(TYPE_ID) REFERENCES @dbschema.@DBPROPTYPE
	CONSTRAINT WIMF_1);


ALTER TABLE @dbschema.@DBPROPENT ADD CONSTRAINT 
	(FOREIGN KEY(PROP_ID) REFERENCES @dbschema.@DBPROP
	ON DELETE CASCADE CONSTRAINT WIMF_2);


ALTER TABLE @dbschema.@DBLONGPROP ADD CONSTRAINT 
	(FOREIGN KEY(PROP_ID) REFERENCES @dbschema.@DBPROP
	ON DELETE CASCADE CONSTRAINT WIMF_3);
			
			
ALTER TABLE @dbschema.@DBLONGPROP ADD CONSTRAINT 
	(FOREIGN KEY(TYPE_ID) REFERENCES @dbschema.@DBPROPTYPE
	CONSTRAINT WIMF_4);


ALTER TABLE @dbschema.@DBLONGPROP ADD CONSTRAINT 
	(FOREIGN KEY(ENTITY_ID) REFERENCES @dbschema.@DBENTITY
	ON DELETE CASCADE CONSTRAINT WIMF_5);
			
			
ALTER TABLE @dbschema.@DBLONGPROP ADD CONSTRAINT 
	(FOREIGN KEY(COMPOSITE) REFERENCES @dbschema.@DBCOMPPROP
	ON DELETE CASCADE CONSTRAINT WIMF_6);
			
			
ALTER TABLE @dbschema.@DBBLOBPROP ADD CONSTRAINT 
	(FOREIGN KEY(PROP_ID) REFERENCES @dbschema.@DBPROP
	ON DELETE CASCADE CONSTRAINT WIMF_7);
			
			
ALTER TABLE @dbschema.@DBBLOBPROP ADD CONSTRAINT 
	(FOREIGN KEY(TYPE_ID) REFERENCES @dbschema.@DBPROPTYPE
	CONSTRAINT WIMF_8);


ALTER TABLE @dbschema.@DBBLOBPROP ADD CONSTRAINT 
	(FOREIGN KEY(ENTITY_ID) REFERENCES @dbschema.@DBENTITY
	ON DELETE CASCADE CONSTRAINT WIMF_9);
			
			
ALTER TABLE @dbschema.@DBBLOBPROP ADD CONSTRAINT 
	(FOREIGN KEY(COMPOSITE) REFERENCES @dbschema.@DBCOMPPROP
	ON DELETE CASCADE CONSTRAINT WIMF_10);


ALTER TABLE @dbschema.@DBDBLPROP ADD CONSTRAINT 
	(FOREIGN KEY(PROP_ID) REFERENCES @dbschema.@DBPROP
	ON DELETE CASCADE CONSTRAINT WIMF_11);
			
			
ALTER TABLE @dbschema.@DBDBLPROP ADD CONSTRAINT 
	(FOREIGN KEY(TYPE_ID) REFERENCES @dbschema.@DBPROPTYPE
	CONSTRAINT WIMF_12);


ALTER TABLE @dbschema.@DBDBLPROP ADD CONSTRAINT 
	(FOREIGN KEY(ENTITY_ID) REFERENCES @dbschema.@DBENTITY
	ON DELETE CASCADE CONSTRAINT WIMF_13);
			
			
ALTER TABLE @dbschema.@DBDBLPROP ADD CONSTRAINT 
	(FOREIGN KEY(COMPOSITE) REFERENCES @dbschema.@DBCOMPPROP
	ON DELETE CASCADE CONSTRAINT WIMF_14);


ALTER TABLE @dbschema.@DBTSPROP ADD CONSTRAINT 
	(FOREIGN KEY(PROP_ID) REFERENCES @dbschema.@DBPROP
	ON DELETE CASCADE CONSTRAINT WIMF_15);
			
			
ALTER TABLE @dbschema.@DBTSPROP ADD CONSTRAINT 
	(FOREIGN KEY(TYPE_ID) REFERENCES @dbschema.@DBPROPTYPE
	CONSTRAINT WIMF_16);


ALTER TABLE @dbschema.@DBTSPROP ADD CONSTRAINT 
	(FOREIGN KEY(ENTITY_ID) REFERENCES @dbschema.@DBENTITY
	ON DELETE CASCADE CONSTRAINT WIMF_17);
			
			
ALTER TABLE @dbschema.@DBTSPROP ADD CONSTRAINT 
	(FOREIGN KEY(COMPOSITE) REFERENCES @dbschema.@DBCOMPPROP
	ON DELETE CASCADE CONSTRAINT WIMF_18);


ALTER TABLE @dbschema.@DBINTPROP ADD CONSTRAINT 
	(FOREIGN KEY(PROP_ID) REFERENCES @dbschema.@DBPROP
	ON DELETE CASCADE CONSTRAINT WIMF_19);
			
			
ALTER TABLE @dbschema.@DBINTPROP ADD CONSTRAINT 
	(FOREIGN KEY(TYPE_ID) REFERENCES @dbschema.@DBPROPTYPE
	CONSTRAINT WIMF_20);


ALTER TABLE @dbschema.@DBINTPROP ADD CONSTRAINT 
	(FOREIGN KEY(ENTITY_ID) REFERENCES @dbschema.@DBENTITY
	ON DELETE CASCADE CONSTRAINT WIMF_21);
			
			
ALTER TABLE @dbschema.@DBINTPROP ADD CONSTRAINT 
	(FOREIGN KEY(COMPOSITE) REFERENCES @dbschema.@DBCOMPPROP
	ON DELETE CASCADE CONSTRAINT WIMF_22);


ALTER TABLE @dbschema.@DBREFPROP ADD CONSTRAINT 
	(FOREIGN KEY(PROP_ID) REFERENCES @dbschema.@DBPROP
	ON DELETE CASCADE CONSTRAINT WIMF_23);
			
			
ALTER TABLE @dbschema.@DBREFPROP ADD CONSTRAINT 
	(FOREIGN KEY(TYPE_ID) REFERENCES @dbschema.@DBPROPTYPE
	CONSTRAINT WIMF_24);


ALTER TABLE @dbschema.@DBREFPROP ADD CONSTRAINT 
	(FOREIGN KEY(ENTITY_ID) REFERENCES @dbschema.@DBENTITY
	ON DELETE CASCADE CONSTRAINT WIMF_25);
			
			
ALTER TABLE @dbschema.@DBREFPROP ADD CONSTRAINT 
	(FOREIGN KEY(COMPOSITE) REFERENCES @dbschema.@DBCOMPPROP
	ON DELETE CASCADE CONSTRAINT WIMF_26);



ALTER TABLE @dbschema.@DBSTRPROP ADD CONSTRAINT 
	(FOREIGN KEY(PROP_ID) REFERENCES @dbschema.@DBPROP
	ON DELETE CASCADE CONSTRAINT WIMF_27);
			
			
ALTER TABLE @dbschema.@DBSTRPROP ADD CONSTRAINT 
	(FOREIGN KEY(TYPE_ID) REFERENCES @dbschema.@DBPROPTYPE
	CONSTRAINT WIMF_28);


ALTER TABLE @dbschema.@DBSTRPROP ADD CONSTRAINT 
	(FOREIGN KEY(ENTITY_ID) REFERENCES @dbschema.@DBENTITY
	ON DELETE CASCADE CONSTRAINT WIMF_29);
			
			
ALTER TABLE @dbschema.@DBSTRPROP ADD CONSTRAINT 
	(FOREIGN KEY(COMPOSITE) REFERENCES @dbschema.@DBCOMPPROP
	ON DELETE CASCADE CONSTRAINT WIMF_30);


ALTER TABLE @dbschema.@DBCOMPREL ADD CONSTRAINT 
	(FOREIGN KEY(COMPOSITE_ID) REFERENCES @dbschema.@DBPROP
	ON DELETE CASCADE CONSTRAINT WIMF_31);


ALTER TABLE @dbschema.@DBCOMPREL ADD CONSTRAINT 
	(FOREIGN KEY(COMPONENT_ID) REFERENCES @dbschema.@DBPROP
	ON DELETE CASCADE CONSTRAINT WIMF_32);
			

ALTER TABLE @dbschema.@DBENTREL ADD CONSTRAINT 
	(FOREIGN KEY(DESCENDANT_ID) REFERENCES @dbschema.@DBENTITY
	ON DELETE CASCADE CONSTRAINT WIMF_33);


ALTER TABLE @dbschema.@DBENTREL ADD CONSTRAINT 
	(FOREIGN KEY(ANCESTOR_ID) REFERENCES @dbschema.@DBENTITY
	ON DELETE CASCADE CONSTRAINT WIMF_34);

			
ALTER TABLE @dbschema.@DBGRPREL ADD CONSTRAINT 
	(FOREIGN KEY(GRP_ID) REFERENCES @dbschema.@DBENTITY
	ON DELETE CASCADE CONSTRAINT WIMF_35);


ALTER TABLE @dbschema.@DBCOMPPROP ADD CONSTRAINT 
	(FOREIGN KEY(PROP_ID) REFERENCES @dbschema.@DBPROP
	ON DELETE CASCADE CONSTRAINT WIMF_36);
			
ALTER TABLE @dbschema.@DBCOMPPROP ADD CONSTRAINT 
	(FOREIGN KEY(ENTITY_ID) REFERENCES @dbschema.@DBENTITY
	ON DELETE CASCADE CONSTRAINT WIMF_37);
			
ALTER TABLE @dbschema.@DBCOMPPROP ADD CONSTRAINT 
	(FOREIGN KEY(COMPOSITE_ID) REFERENCES @dbschema.@DBCOMPPROP
	ON DELETE CASCADE CONSTRAINT WIMF_38);
			
ALTER TABLE @dbschema.@DBACCT ADD CONSTRAINT 
        (FOREIGN KEY (ENTITY_ID) REFERENCES @dbschema.@DBENTITY
        ON DELETE CASCADE CONSTRAINT WIMF_39);
