--------------- Begin Copyright - Do not add comments here --------------
--
-- Licensed Materials - Property of IBM
--
-- Restricted Materials of IBM
--
-- Virtual Member Manager
--
-- (C) Copyright IBM Corp. 2005, 2010
--
-- US Government Users Restricted Rights - Use, duplication or
-- disclosure restricted by GSA ADP Schedule Contract with
-- IBM Corp.
--
----------------------------- End Copyright -----------------------------
ALTER TABLE @dbschema.@DBPROP
	ADD CONSTRAINT WIMF_1
		FOREIGN KEY(TYPE_ID)
			REFERENCES @dbschema.@DBPROPTYPE
			ON DELETE NO ACTION;


ALTER TABLE @dbschema.@DBPROPENT
	ADD CONSTRAINT WIMF_2
		FOREIGN KEY(PROP_ID)
			REFERENCES @dbschema.@DBPROP
			ON DELETE CASCADE;


ALTER TABLE @dbschema.@DBLONGPROP
	ADD CONSTRAINT WIMF_3
		FOREIGN KEY(PROP_ID)
			REFERENCES @dbschema.@DBPROP
			ON DELETE CASCADE;
			
			
ALTER TABLE @dbschema.@DBLONGPROP
	ADD CONSTRAINT WIMF_4
		FOREIGN KEY(TYPE_ID)
			REFERENCES @dbschema.@DBPROPTYPE
			ON DELETE NO ACTION;


ALTER TABLE @dbschema.@DBLONGPROP
	ADD CONSTRAINT WIMF_5
		FOREIGN KEY(ENTITY_ID)
			REFERENCES @dbschema.@DBENTITY
			ON DELETE CASCADE;
			
			
ALTER TABLE @dbschema.@DBBLOBPROP
	ADD CONSTRAINT WIMF_7
		FOREIGN KEY(PROP_ID)
			REFERENCES @dbschema.@DBPROP
			ON DELETE CASCADE;
			
			
ALTER TABLE @dbschema.@DBBLOBPROP
	ADD CONSTRAINT WIMF_8
		FOREIGN KEY(TYPE_ID)
			REFERENCES @dbschema.@DBPROPTYPE
			ON DELETE NO ACTION;


ALTER TABLE @dbschema.@DBBLOBPROP
	ADD CONSTRAINT WIMF_9
		FOREIGN KEY(ENTITY_ID)
			REFERENCES @dbschema.@DBENTITY
			ON DELETE CASCADE;


ALTER TABLE @dbschema.@DBDBLPROP
	ADD CONSTRAINT WIMF_11
		FOREIGN KEY(PROP_ID)
			REFERENCES @dbschema.@DBPROP
			ON DELETE CASCADE;
			
			
ALTER TABLE @dbschema.@DBDBLPROP
	ADD CONSTRAINT WIMF_12
		FOREIGN KEY(TYPE_ID)
			REFERENCES @dbschema.@DBPROPTYPE
			ON DELETE NO ACTION;


ALTER TABLE @dbschema.@DBDBLPROP
	ADD CONSTRAINT WIMF_13
		FOREIGN KEY(ENTITY_ID)
			REFERENCES @dbschema.@DBENTITY
			ON DELETE CASCADE;


ALTER TABLE @dbschema.@DBTSPROP
	ADD CONSTRAINT WIMF_15
		FOREIGN KEY(PROP_ID)
			REFERENCES @dbschema.@DBPROP
			ON DELETE CASCADE;
			
			
ALTER TABLE @dbschema.@DBTSPROP
	ADD CONSTRAINT WIMF_16
		FOREIGN KEY(TYPE_ID)
			REFERENCES @dbschema.@DBPROPTYPE
			ON DELETE NO ACTION;


ALTER TABLE @dbschema.@DBTSPROP
	ADD CONSTRAINT WIMF_17
		FOREIGN KEY(ENTITY_ID)
			REFERENCES @dbschema.@DBENTITY
			ON DELETE CASCADE;


ALTER TABLE @dbschema.@DBINTPROP
	ADD CONSTRAINT WIMF_19
		FOREIGN KEY(PROP_ID)
			REFERENCES @dbschema.@DBPROP
			ON DELETE CASCADE;
			
			
ALTER TABLE @dbschema.@DBINTPROP
	ADD CONSTRAINT WIMF_20
		FOREIGN KEY(TYPE_ID)
			REFERENCES @dbschema.@DBPROPTYPE
			ON DELETE NO ACTION;


ALTER TABLE @dbschema.@DBINTPROP
	ADD CONSTRAINT WIMF_21
		FOREIGN KEY(ENTITY_ID)
			REFERENCES @dbschema.@DBENTITY
			ON DELETE CASCADE;


ALTER TABLE @dbschema.@DBREFPROP
	ADD CONSTRAINT WIMF_23
		FOREIGN KEY(PROP_ID)
			REFERENCES @dbschema.@DBPROP
			ON DELETE CASCADE;
			
			
ALTER TABLE @dbschema.@DBREFPROP
	ADD CONSTRAINT WIMF_24
		FOREIGN KEY(TYPE_ID)
			REFERENCES @dbschema.@DBPROPTYPE
			ON DELETE NO ACTION;


ALTER TABLE @dbschema.@DBREFPROP
	ADD CONSTRAINT WIMF_25
		FOREIGN KEY(ENTITY_ID)
			REFERENCES @dbschema.@DBENTITY
			ON DELETE CASCADE;



ALTER TABLE @dbschema.@DBSTRPROP
	ADD CONSTRAINT WIMF_27
		FOREIGN KEY(PROP_ID)
			REFERENCES @dbschema.@DBPROP
			ON DELETE CASCADE;
			
			
ALTER TABLE @dbschema.@DBSTRPROP
	ADD CONSTRAINT WIMF_28
		FOREIGN KEY(TYPE_ID)
			REFERENCES @dbschema.@DBPROPTYPE
			ON DELETE NO ACTION;


ALTER TABLE @dbschema.@DBSTRPROP
	ADD CONSTRAINT WIMF_29
		FOREIGN KEY(ENTITY_ID)
			REFERENCES @dbschema.@DBENTITY
			ON DELETE CASCADE;


ALTER TABLE @dbschema.@DBCOMPREL
	ADD CONSTRAINT WIMF_31
		FOREIGN KEY(COMPOSITE_ID)
			REFERENCES @dbschema.@DBPROP
			ON DELETE CASCADE;


ALTER TABLE @dbschema.@DBCOMPREL
	ADD CONSTRAINT WIMF_32
		FOREIGN KEY(COMPONENT_ID)
			REFERENCES @dbschema.@DBPROP
			ON DELETE NO ACTION;
			

ALTER TABLE @dbschema.@DBENTREL
	ADD CONSTRAINT WIMF_33
		FOREIGN KEY(DESCENDANT_ID)
			REFERENCES @dbschema.@DBENTITY
			ON DELETE CASCADE;

			
ALTER TABLE @dbschema.@DBGRPREL
	ADD CONSTRAINT WIMF_35
		FOREIGN KEY(GRP_ID)
			REFERENCES @dbschema.@DBENTITY
			ON DELETE CASCADE;


ALTER TABLE @dbschema.@DBCOMPPROP
	ADD CONSTRAINT WIMF_36
		FOREIGN KEY(PROP_ID)
			REFERENCES @dbschema.@DBPROP
			ON DELETE CASCADE;
			
ALTER TABLE @dbschema.@DBCOMPPROP
	ADD CONSTRAINT WIMF_37
		FOREIGN KEY(ENTITY_ID)
			REFERENCES @dbschema.@DBENTITY
			ON DELETE CASCADE;
			
			
ALTER TABLE @dbschema.@DBACCT
       	ADD CONSTRAINT WIMF_39
              	FOREIGN KEY (ENTITY_ID)
                    	REFERENCES @dbschema.@DBENTITY
                   	ON DELETE CASCADE;
